### ISSUE TITLE
document setup for Mac ARM users with python built for x86_64

### ISSUE THREAD

**Issue by justaddcoffee** [justaddcoffee/rustsim#1]
@cmungall @hrshdhgd @caufieldjh 
Mac ARM M1 users can (and I am) experience the same issue in `rustsim` that we saw repeatedly with GRAPE when trying to install and run Rust code. 

This problem results from python, rosetta and (most) virtual environments not playing well together (not something specific to GRAPE)

**To reproduce the problem:**

```
~/PycharmProjects/rustsim main $ file `which python3` # note that python is built for x86_64 
/usr/local/bin/python3: Mach-O 64-bit executable x86_64
~/PycharmProjects/rustsim main $ python3 -m venv venv
~/PycharmProjects/rustsim main $ source venv/bin/activate
(venv) ~/PycharmProjects/rustsim main $ which maturin
/Users/jtr4v/.cargo/bin/maturin
(venv) ~/PycharmProjects/rustsim main $ maturin develop
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at python
   Compiling pyo3-build-config v0.18.0
   Compiling pyo3-ffi v0.18.0
   Compiling pyo3 v0.18.0
   Compiling rustsim v0.1.0 (/Users/jtr4v/PycharmProjects/rustsim)
    Finished dev [unoptimized + debuginfo] target(s) in 6.49s
⚠  Warning: Couldn't find the symbol `PyInit_rustsim` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `rustsim` as module name
(venv) ~/PycharmProjects/rustsim main $ python3
Python 3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rustsim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jtr4v/PycharmProjects/rustsim/venv/lib/python3.10/site-packages/rustsim/__init__.py", line 1, in <module>
    from .rustsim import *
ImportError: dlopen(/Users/jtr4v/PycharmProjects/rustsim/venv/lib/python3.10/site-packages/rustsim/rustsim.cpython-310-darwin.so, 0x0002): tried: '/Users/jtr4v/PycharmProjects/rustsim/venv/lib/python3.10/site-packages/rustsim/rustsim.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
```

**The fix:**

The workaround/fix is to install a python that is built for ARM processors and built rustsim with that python. One way to do this:

1) install conda as described [here](https://towardsdatascience.com/how-to-manage-conda-environments-on-an-apple-silicon-m1-mac-1e29cb3bad12)

2) make a virtual environment that uses a python built for ARM:
```
~/PycharmProjects/rustsim main $ conda create -n myenv python=3.9

[snip]
#
# To activate this environment, use
#
#     $ conda activate myenv
#
# To deactivate an active environment, use
#
#     $ conda deactivate

~/PycharmProjects/rustsim main $ conda activate myenv
(myenv) ~/PycharmProjects/rustsim main $ file `which python` # now we are using arm64 python
/Users/jtr4v/anaconda3/envs/myenv/bin/python: Mach-O 64-bit executable arm64
(myenv) ~/PycharmProjects/rustsim main $ which maturin
/Users/jtr4v/.cargo/bin/maturin
(myenv) ~/PycharmProjects/rustsim main $ maturin develop
🔗 Found pyo3 bindings
🐍 Found CPython 3.9 at python3
   Compiling pyo3-build-config v0.18.0
   Compiling pyo3-ffi v0.18.0
   Compiling pyo3 v0.18.0
   Compiling rustsim v0.1.0 (/Users/jtr4v/PycharmProjects/rustsim)
    Finished dev [unoptimized + debuginfo] target(s) in 4.01s
⚠  Warning: Couldn't find the symbol `PyInit_rustsim` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `rustsim` as module name
(myenv) ~/PycharmProjects/rustsim main $ python3
Python 3.9.16 (main, Jan 11 2023, 10:02:19)
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rustsim
```

**Comment by justaddcoffee** [comment]
If this makes sense, maybe we can add this to the docs somewhere?

**Comment by caufieldjh** [comment]
@justaddcoffee what happens if you run `maturin build` instead of `maturin develop`?

It's a relatively simple workaround but I'm increasingly thinking we should have the ability to build python packages for this architecture - I _think_ maturin and the [maturin-action](https://github.com/PyO3/maturin-action) are capable of this now

**Comment by justaddcoffee** [comment]
> It's a relatively simple workaround but I'm increasingly thinking we should have the ability to build (as in, automate the build process and get the appropriate wheels for) python packages for this architecture - I think maturin and the [maturin-action](https://github.com/PyO3/maturin-action) are capable of this now

Good idea! I think @cmungall pointed out a python library we could use to build ARM wheels on Linux (therefore we could build these wheels in github actions). Maybe we can hack on this together

> @justaddcoffee what happens if you run maturin build instead of maturin develop?

Same result if you `maturin build` and then `maturin develop` AFAICT:

```
(venv) ~/PycharmProjects/rustsim main $ maturin build
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at python3.8, CPython 3.9 at python3.9, CPython 3.10 at python3.10
📦 Built source distribution to /Users/jtr4v/PycharmProjects/rustsim/target/wheels/rustsim-0.1.0.tar.gz
   Compiling pyo3-build-config v0.18.0
   Compiling pyo3-ffi v0.18.0
   Compiling pyo3 v0.18.0
   Compiling rustsim v0.1.0 (/Users/jtr4v/PycharmProjects/rustsim)
    Finished dev [unoptimized + debuginfo] target(s) in 3.21s
⚠  Warning: Couldn't find the symbol `PyInit_rustsim` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `rustsim` as module name
📦 Built wheel for CPython 3.8 to /Users/jtr4v/PycharmProjects/rustsim/target/wheels/rustsim-0.1.0-cp38-cp38-macosx_11_0_arm64.whl
   Compiling pyo3-build-config v0.18.0
   Compiling pyo3-ffi v0.18.0
   Compiling pyo3 v0.18.0
   Compiling rustsim v0.1.0 (/Users/jtr4v/PycharmProjects/rustsim)
    Finished dev [unoptimized + debuginfo] target(s) in 3.32s
⚠  Warning: Couldn't find the symbol `PyInit_rustsim` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `rustsim` as module name
📦 Built wheel for CPython 3.9 to /Users/jtr4v/PycharmProjects/rustsim/target/wheels/rustsim-0.1.0-cp39-cp39-macosx_11_0_arm64.whl
   Compiling pyo3-build-config v0.18.0
   Compiling pyo3-ffi v0.18.0
   Compiling pyo3 v0.18.0
   Compiling rustsim v0.1.0 (/Users/jtr4v/PycharmProjects/rustsim)
    Finished dev [unoptimized + debuginfo] target(s) in 3.40s
⚠  Warning: Couldn't find the symbol `PyInit_rustsim` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `rustsim` as module name
📦 Built wheel for CPython 3.10 to /Users/jtr4v/PycharmProjects/rustsim/target/wheels/rustsim-0.1.0-cp310-cp310-macosx_11_0_arm64.whl
(venv) ~/PycharmProjects/rustsim main $ python3
Python 3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rustsim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jtr4v/PycharmProjects/rustsim/venv/lib/python3.10/site-packages/rustsim/__init__.py", line 1, in <module>
    from .rustsim import *
ImportError: dlopen(/Users/jtr4v/PycharmProjects/rustsim/venv/lib/python3.10/site-packages/rustsim/rustsim.cpython-310-darwin.so, 0x0002): tried: '/Users/jtr4v/PycharmProjects/rustsim/venv/lib/python3.10/site-packages/rustsim/rustsim.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
```

**Comment by caufieldjh** [comment]
> Same result if you maturin build and then maturin develop AFAICT:

OK, that's good to know. I was curious if the build process would be sensitive to the platform architecture but it's primarily basing it on whatever Python is expecting to use, I suppose.

An example using `maturin-action`: https://github.com/delta-io/delta-rs/blob/c0e94632b28ecadd75617653e16ba1c5242600d8/.github/workflows/python_release.yml

**Comment by justaddcoffee** [comment]
Looks like the README now has a section on Mac support - thanks! Closing this
